name: Squash Commit History

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  squash:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Squash history
        run: |
          git checkout --orphan temp-branch
          git add -A
          git commit -m "Latest resume version"
          git branch -D main
          git branch -m main
          git push -f origin main
